# Hiring Analytics #

In [2]:
# !pip install word2number

In [1]:
import numpy as np
import pandas as pd
import matplotlib 
from matplotlib import pyplot as plt
import sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import math
from word2number import w2n
%matplotlib inline

In [2]:
df = pd.read_csv('./Hiring.csv')
df.head(10)

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

## My attempt ##

In [3]:
exp = list(df.experience)
exp

[nan, nan, 'five', 'two', 'seven', 'three', 'ten', 'eleven']

In [4]:
for i in range(2,len(exp)):
    num = w2n.word_to_num(exp[i])
    exp[i] = num

exp[0], exp[1] = 0, 0


In [5]:
exp = pd.DataFrame(exp, columns = ['experience'])
exp

experience
0           0
1           0
2           5
3           2
4           7
5           3
6          10
7          11

In [6]:
df.drop('experience', axis = 1, inplace = True)
df = pd.concat([df, exp], axis = 1).reindex(df.index)
df

test_score(out of 10)  interview_score(out of 10)  salary($)  experience
0                    8.0                           9      50000           0
1                    8.0                           6      45000           0
2                    6.0                           7      60000           5
3                   10.0                          10      65000           2
4                    9.0                           6      70000           7
5                    7.0                          10      62000           3
6                    NaN                           7      72000          10
7                    7.0                           8      80000          11

In [8]:
median_scores = math.floor(df[['test_score(out of 10)']].median())
median_scores

8

In [11]:
df[['test_score(out of 10)']] = df[['test_score(out of 10)']].fillna(median_scores)

In [12]:
df

test_score(out of 10)  interview_score(out of 10)  salary($)  experience
0                    8.0                           9      50000           0
1                    8.0                           6      45000           0
2                    6.0                           7      60000           5
3                   10.0                          10      65000           2
4                    9.0                           6      70000           7
5                    7.0                          10      62000           3
6                    8.0                           7      72000          10
7                    7.0                           8      80000          11

In [13]:
reg = LinearRegression()
reg.fit(df[['test_score(out of 10)', 'interview_score(out of 10)', 'experience']], df[['salary($)']])

LinearRegression()

In [14]:
reg.coef_

array([[1845.70596798, 2205.24017467, 2812.95487627]])

In [15]:
reg.intercept_

array([17737.26346434])

In [16]:
reg.predict([[9, 6, 2]])

D:\anaconda3\envs\MLpractice\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[53205.96797671]])

In [17]:
reg.predict([[10, 10, 12]])

D:\anaconda3\envs\MLpractice\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[92002.18340611]])

## Corrections ##

In [3]:
df.experience = df.experience.fillna("zero")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0       zero                    8.0                           9      50000
1       zero                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [5]:
df.experience = df.experience.apply(w2n.word_to_num)
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    NaN                           7      72000
7          11                    7.0                           8      80000

In [7]:
median_test_score = math.floor(df['test_score(out of 10)'].mean())
median_test_score

7

In [8]:
df['test_score(out of 10)'] = df['test_score(out of 10)'].fillna(median_test_score)
df


experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

In [11]:
reg = LinearRegression()
reg.fit(df[['experience','test_score(out of 10)','interview_score(out of 10)']],df['salary($)'])

LinearRegression()

In [12]:
reg.predict([[2,9,6]])

D:\anaconda3\envs\MLpractice\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53713.86677124])

In [13]:
reg.predict([[12,10,10]])

D:\anaconda3\envs\MLpractice\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([93747.79628651])